#!/bin/bash

if [ "$OSTYPE" == "linux-gnu" ]; then
    READLINK=readlink
else
    # Assuming this means OS X, and `coreutils` is installed:
    # https://stackoverflow.com/a/4031502/27641.
    READLINK=greadlink
fi

check-symlink() {
    SOURCE=$1
    TARGET=$2

    CURRENT_TARGET=$($READLINK -f "$SOURCE") || true

    if [[ "$CURRENT_TARGET" != "$TARGET" ]]; then
        if [[ -e $SOURCE && ! -L $SOURCE ]]; then
            if [[ -f "$SOURCE" ]] && cmp --silent "$SOURCE" "$TARGET"; then
                echo "WARNING! Source file $SOURCE is identical to $TARGET; removing $SOURCE."
                rm "$SOURCE"
            else
                echo "ERROR: File $SOURCE should be a symlink pointing to $TARGET but it already exists and is not a symlink and is not identical, cannot proceed - please check."
                exit 1
            fi
        fi

        echo "Symlink $SOURCE does not exist or does not point to $TARGET, making link."
        rm -fv "$SOURCE"
        ONE_DIRNAME=$(dirname "$SOURCE")

        realpath --relative-to=/tmp /tmp 2>&1 | grep --quiet 'unrecognized option'
        if [[ $? -ne 0 ]]; then
            TARGET_TO_USE=$(realpath "$TARGET")
        else
            TARGET_TO_USE=$(realpath --relative-to="$ONE_DIRNAME" "$TARGET")
        fi

        mkdir -pv "$ONE_DIRNAME"
        (cd "$ONE_DIRNAME" && ln -sv "$TARGET_TO_USE" "$SOURCE")
    fi
}

check-stale-link() {
    if [[ -L $1 ]]; then
        rm "$1"
    fi
}

check-symlink-if-targetdir() {
    if [[ -d "$2" ]]; then
        check-symlink "$1" "$2"
    else
        check-stale-link "$1"
    fi
}

check-symlink-if-targetfile() {
    if [[ -f "$2" ]]; then
        check-symlink "$1" "$2"
    else
        check-stale-link "$1"
    fi
}

check-symlink-if-command() {
    command -v "$1" >/dev/null 2>&1 && rc=$? || rc=$?
    if [ $rc -eq 0 ]; then
        check-symlink "$2" "$3"
    else
        check-stale-link "$2"
    fi
}

check-symlink-if-directory() {
    if [[ -d "$1" ]]; then
        check-symlink "$2" "$3"
    else
        check-stale-link "$2"
    fi
}
